CREATE TABLE IF NOT EXISTS pet (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    species VARCHAR(50) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    birth_date DATE,
    size VARCHAR(20),
    castration_receipt TEXT,
    vaccination_receipt TEXT,
    street VARCHAR(255),
    number VARCHAR(20),
    neighborhood VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(50),
    health TEXT,
    about TEXT,
    photo1 TEXT,
    photo2 TEXT,
    photo3 TEXT,
    owner_id BIGINT NOT NULL,
    contact_option VARCHAR(50),
    available BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);
